### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Daiyukai** [lyupin/Visualize-DXY-2019-nCov-Data#1]
我的电脑上mac 导入模块 出来的图片上乱码，改了那个位置的mpl.rcParams['font.sans-serif'] = ['SimHei'] # 'Arial', 'SimHei'的字体，出来的图片还是乱码。中文z

**Comment by lyupin** [comment]
附上未被github存档的对话：

3/19：
问题已经解决了，谢谢您哈
问题如下：

1、我将{:d}改成了{:f}成功运行
ax.plot(df_tmp['updateDate'], df_tmp[columnNames[iCol]], '.-',label = cityNames[i]+'({:s} {:f})'.format(label_latestValue, df_tmp[columnNames[iCol]].iloc[-1]))
2、这里我将
mpl.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.sans-serif'] = ['Microsoft YaHei'] # 'Arial', 'SimHei'
改成：
plt.rcParams['font.sans-serif']=['SimHei']
plt.rcParams['axes.unicode_minus'] = False
成功在保存图片里显示中文。
再次感谢您提供的代码。


2/25：
我不用mac. 你看看这篇里的办法吧，https://blog.csdn.net/lztttao/article/details/99697813
